# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[(None, '---User Type---'), ('Recruiter', 'Recruiter'), ('Prospective Employer', 'Prospective Employer'), ('Friend', 'Friend')], default=None, max_length=255)),
            ],
        ),
    ]
